#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -Wall -g -Wall -ggdb -pthread -D_REENTRANT -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/SDL2 -I/usr/include/SDL2 -D_REENTRANT
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG =
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS) -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSDL2_image -lSDL2 -L/usr/lib -lSDL2 -lm -lncurses -rdynamic
OBJDIR_DEBUG = obj/debug
DEP_DEBUG = 
OUT_DEBUG = bin/SimulationHumainsVsZombies_debug

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -Wall -ggdb -pthread -D_REENTRANT -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/SDL2 -I/usr/include/SDL2 -D_REENTRANT -DNDEBUG
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSDL2_image -lSDL2 -L/usr/lib -lSDL2 -lm -lncurses -rdynamic
OBJDIR_RELEASE = obj/release
DEP_RELEASE = 
OUT_RELEASE = bin/SimulationHumainsVsZombies_release

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/terrain.o $(OBJDIR_DEBUG)/src/simulation_gtk.o $(OBJDIR_DEBUG)/src/simulation.o $(OBJDIR_DEBUG)/src/personnage.o $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/SDL2/affichage_SDL.o $(OBJDIR_DEBUG)/src/coordonnees.o $(OBJDIR_DEBUG)/src/caseDeplacement.o $(OBJDIR_DEBUG)/src/SDL2/simulation_SDL2.o $(OBJDIR_DEBUG)/src/SDL2/initialisation_SDL.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/terrain.o $(OBJDIR_RELEASE)/src/simulation_gtk.o $(OBJDIR_RELEASE)/src/simulation.o $(OBJDIR_RELEASE)/src/personnage.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/SDL2/affichage_SDL.o $(OBJDIR_RELEASE)/src/coordonnees.o $(OBJDIR_RELEASE)/src/caseDeplacement.o $(OBJDIR_RELEASE)/src/SDL2/simulation_SDL2.o $(OBJDIR_RELEASE)/src/SDL2/initialisation_SDL.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/src/SDL2 || mkdir -p $(OBJDIR_DEBUG)/src/SDL2

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/terrain.o: src/terrain.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/terrain.c -o $(OBJDIR_DEBUG)/src/terrain.o

$(OBJDIR_DEBUG)/src/simulation_gtk.o: src/simulation_gtk.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/simulation_gtk.c -o $(OBJDIR_DEBUG)/src/simulation_gtk.o

$(OBJDIR_DEBUG)/src/simulation.o: src/simulation.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/simulation.c -o $(OBJDIR_DEBUG)/src/simulation.o

$(OBJDIR_DEBUG)/src/personnage.o: src/personnage.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/personnage.c -o $(OBJDIR_DEBUG)/src/personnage.o

$(OBJDIR_DEBUG)/src/main.o: src/main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.c -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/SDL2/affichage_SDL.o: src/SDL2/affichage_SDL.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SDL2/affichage_SDL.c -o $(OBJDIR_DEBUG)/src/SDL2/affichage_SDL.o

$(OBJDIR_DEBUG)/src/coordonnees.o: src/coordonnees.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/coordonnees.c -o $(OBJDIR_DEBUG)/src/coordonnees.o

$(OBJDIR_DEBUG)/src/caseDeplacement.o: src/caseDeplacement.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/caseDeplacement.c -o $(OBJDIR_DEBUG)/src/caseDeplacement.o

$(OBJDIR_DEBUG)/src/SDL2/simulation_SDL2.o: src/SDL2/simulation_SDL2.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SDL2/simulation_SDL2.c -o $(OBJDIR_DEBUG)/src/SDL2/simulation_SDL2.o

$(OBJDIR_DEBUG)/src/SDL2/initialisation_SDL.o: src/SDL2/initialisation_SDL.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SDL2/initialisation_SDL.c -o $(OBJDIR_DEBUG)/src/SDL2/initialisation_SDL.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/src/SDL2

before_release: 
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE)/src/SDL2 || mkdir -p $(OBJDIR_RELEASE)/src/SDL2

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/terrain.o: src/terrain.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/terrain.c -o $(OBJDIR_RELEASE)/src/terrain.o

$(OBJDIR_RELEASE)/src/simulation_gtk.o: src/simulation_gtk.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/simulation_gtk.c -o $(OBJDIR_RELEASE)/src/simulation_gtk.o

$(OBJDIR_RELEASE)/src/simulation.o: src/simulation.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/simulation.c -o $(OBJDIR_RELEASE)/src/simulation.o

$(OBJDIR_RELEASE)/src/personnage.o: src/personnage.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/personnage.c -o $(OBJDIR_RELEASE)/src/personnage.o

$(OBJDIR_RELEASE)/src/main.o: src/main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.c -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/SDL2/affichage_SDL.o: src/SDL2/affichage_SDL.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SDL2/affichage_SDL.c -o $(OBJDIR_RELEASE)/src/SDL2/affichage_SDL.o

$(OBJDIR_RELEASE)/src/coordonnees.o: src/coordonnees.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/coordonnees.c -o $(OBJDIR_RELEASE)/src/coordonnees.o

$(OBJDIR_RELEASE)/src/caseDeplacement.o: src/caseDeplacement.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/caseDeplacement.c -o $(OBJDIR_RELEASE)/src/caseDeplacement.o

$(OBJDIR_RELEASE)/src/SDL2/simulation_SDL2.o: src/SDL2/simulation_SDL2.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SDL2/simulation_SDL2.c -o $(OBJDIR_RELEASE)/src/SDL2/simulation_SDL2.o

$(OBJDIR_RELEASE)/src/SDL2/initialisation_SDL.o: src/SDL2/initialisation_SDL.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SDL2/initialisation_SDL.c -o $(OBJDIR_RELEASE)/src/SDL2/initialisation_SDL.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)/src/SDL2

doxygen:
	doxygen doc/Doxyfile

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

